In [1]:
# Loading packages

import pandas as pd
import numpy as np
import os
import sys
import re

In [2]:
# Working directory is set to same location as where the script is saved

os.chdir(sys.path[0])

In [3]:
# Defining a function for performing data quality analysis

# Please follow the instructions for inputs:
    # file_type can equal either 'Excel' or 'Csv'
    # path is the location of the data
    # which_columns is the index for columns to examine
        # Eg. For examining columns 1-3, enter [1,2,3] (remember to include brackets, even for only one column)
    # search_criteria is the pattern to match; multiple patterns can be matched
        # Eg. Search criteria of ["004", "ABC"] (remember to include brackets, even for only one pattern)
    # action allows three options: "remove", "filter", "replace" (remember to include quotes)
        # Eg. To remove all rows which match the pattern(s), select "remove"
    # criteria_type defaults to 'regex' for regular expressions; for literal matches, change to 'literal'
    # replace_with defaults to 'None' but should be changed if "replace" action is selected
        # Eg. For search criteria of ["004", "ABC"], replace with ["ITSQ", "1_"]

# Note:
# For regex matches, include '^' at the beginning of the pattern to look at the beginning, and '$' at the end of the pattern to look at the end
# If these are not included, any part of the string will be matched to the pattern
# For literal matches, it is not possible to specify whether to look at the beginning or end of the string; only possible with regex matches

# The function will return the following outputs:
    # df: A dataframe object of the original data with additional columns for indicating where matches occurred
    # result: A dataframe object of the original data after the specified action ("remove", "filter", "replace") has been performed

def DQA(file_type, path, which_columns, search_criteria, action, criteria_type = 'regex', replace_with = None):
    
    global df
    if file_type == 'Excel':
        df = pd.read_excel(path)
    if file_type == 'Csv':
        df = pd.read_csv(path)
    
    df = df.astype(str)
    
    col_names = df.columns.values
    
    if criteria_type == 'literal':
        search_criteria = [re.escape(sub) for sub in search_criteria]
    
    append_str = '_flag'
    
    index = np.array(which_columns)-1
    index = index.tolist()
    
    col_names_search = col_names[index]
    col_names_append = [sub + append_str for sub in col_names_search]
    
    for i in range(len(col_names_append)):
        df[col_names_append[i]] = df.iloc[: , i].str.contains('|'.join(search_criteria))
    
    df = df.replace({True: 'Anomaly', False: ''})
    
    global result
    if action == 'filter':
        result = df[df.apply(lambda r: r.str.contains('Anomaly').any(), axis=1)]
        result.reset_index(inplace=True, drop=True)
        result = result.drop(df.filter(regex='_flag').columns, axis=1)
    if action == 'remove':
        result = df[df.apply(lambda r: ~r.str.contains('Anomaly').any(), axis=1)]
        result.reset_index(inplace=True, drop=True)
        result = result.drop(df.filter(regex='_flag').columns, axis=1)
    if action == 'replace':
        result = df.copy()
        for i in range(len(col_names_search)):
            for s in range(len(search_criteria)):
                result[col_names_search[i]] = result.iloc[: , i].str.replace(search_criteria[s], replace_with[s])
        result.reset_index(inplace=True, drop=True)
        result = result.drop(df.filter(regex='_flag').columns, axis=1)

In [4]:
# Testing the function
 
DQA('Excel', 'sample_data.xlsx', [1, 2, 3], ['^000' , '^454'], 'replace', replace_with = ['', ''])

# file_type = 'Excel' because data is saved as Excel file

# path = 'sample_data.xlsx' because the code knows to look in the same directory; if data is saved in a different directory/folder, then user would have to write out the entire file path

# which_columns = [1, 2, 3] in order to look for matches in columns 1-3 of the data

# search_criteria = ['^000', '^454'] in order to look for those particular patterns

# action = 'replace' in order to replace matched patterns

# replace_with = ['', ''] where pattern '^000' and '^454' will be replaced with ''

In [5]:
# Understand where a match or "Anomaly" occurred

df

,Account_ID,Event_ID,Transaction_Number,Column_A,Column_B,Column_C,Account_ID_flag,Event_ID_flag,Transaction_Number_flag
0,A0002,12000060,2460000042,004397A887,009655B320,002222C470,,,
1,A0018,12000061,2460000042,004397A888,009655B321,002222C471,,,
2,A00214,12000062,2460000042,004397A889,009655B322,002222C472,,,
3,A00320,12000063,2460000042,004397A890,009655B323,002222C473,,,
4,A00426,12000064,2460000042,004397A891,009655B324,002222C474,,,
5,000A6542,12000065,2460000042,004397A892,009655B325,002222C475,Anomaly,,
6,000A6547,12000066,2460000042,004397A893,009655B326,002222C476,Anomaly,,
7,000A6552,12000067,2460000042,004397A894,009655B327,002222C477,Anomaly,,
8,000A6557,12000068,2460000042,004397A895,009655B328,002222C478,Anomaly,,
9,000A6562,12000069,2460000042,004397A896,009655B329,002222C479,Anomaly,,
10,000A6567,12000070,2460000042,004397A897,009655B330,002222C480,Anomaly,,
11,000A6572,12000071,2460000042,004397A898,009655B331,002222C481,Anomaly,,
12,000A6577,12000072,2460000042,004397A899,009655B332,002222C482,Anomaly,,
13,000A6582,12000073,2460000042,004397A900,009655B333,002222C483,Anomaly,,
14,839BB45P,45478901,265945600,004397A901,009655B334,002222C484,,Anomaly,
15,840BB45P,45478902,265945601,004397A902,009655B335,002222C485,,Anomaly,
16,841BB45P,45478903,265945602,004397A903,009655B336,002222C486,,Anomaly,
17,842BB45P,45478904,265945603,004397A904,009655B337,002222C487,,Anomaly,
18,843BB45P,45478905,265945604,004397A905,009655B338,002222C488,,Anomaly,
19,844BB45P,45478906,265945605,004397A906,009655B339,002222C489,,Anomaly,
20,845BB45P,45478907,265945606,004397A907,009655B340,002222C490,,Anomaly,
21,846BB45P,45478908,265945607,004397A908,009655B341,002222C491,,Anomaly,
22,847BB45P,45478909,265945608,004397A909,009655B342,002222C492,,Anomaly,
23,848BB45P,45478910,265945609,004397A910,009655B343,002222C493,,Anomaly,
24,849BB45P,45478911,265945610,004397A911,009655B344,002222C494,,Anomaly,
25,850BB45P,45478912,265945611,004397A912,009655B345,002222C495,,Anomaly,
26,851BB45P,45478913,265945612,004397A913,009655B346,002222C496,,Anomaly,
27,852BB45P,45478914,265945613,004397A914,009655B347,002222C497,,Anomaly,
28,853BB45P,45478915,265945614,004397A915,009655B348,002222C498,,Anomaly,
29,854BB45P,45478916,265945615,004397A916,009655B349,002222C499,,Anomaly,
30,855BB45P,45478917,265945616,004397A917,009655B350,002222C500,,Anomaly,
31,856BB45P,45478918,265945617,004397A918,009655B351,002222C501,,Anomaly,
32,857BB45P,45478919,265945618,004397A919,009655B352,002222C502,,Anomaly,
33,858BB45P,45478920,265945619,004397A920,009655B353,002222C503,,Anomaly,
34,859BB45P,45478921,265945620,004397A921,009655B354,002222C504,,Anomaly,

In [6]:
# See what data looks like after performing the action

result

   Account_ID  Event_ID Transaction_Number    Column_A    Column_B    Column_C
0       A0002  12000060         2460000042  004397A887  009655B320  002222C470
1       A0018  12000061         2460000042  004397A888  009655B321  002222C471
2      A00214  12000062         2460000042  004397A889  009655B322  002222C472
3      A00320  12000063         2460000042  004397A890  009655B323  002222C473
4      A00426  12000064         2460000042  004397A891  009655B324  002222C474
5       A6542  12000065         2460000042  004397A892  009655B325  002222C475
6       A6547  12000066         2460000042  004397A893  009655B326  002222C476
7       A6552  12000067         2460000042  004397A894  009655B327  002222C477
8       A6557  12000068         2460000042  004397A895  009655B328  002222C478
9       A6562  12000069         2460000042  004397A896  009655B329  002222C479
10      A6567  12000070         2460000042  004397A897  009655B330  002222C480
11      A6572  12000071         2460000042  004397A898  009655B331  002222C481
12      A6577  12000072         2460000042  004397A899  009655B332  002222C482
13      A6582  12000073         2460000042  004397A900  009655B333  002222C483
14   839BB45P     78901          265945600  004397A901  009655B334  002222C484
15   840BB45P     78902          265945601  004397A902  009655B335  002222C485
16   841BB45P     78903          265945602  004397A903  009655B336  002222C486
17   842BB45P     78904          265945603  004397A904  009655B337  002222C487
18   843BB45P     78905          265945604  004397A905  009655B338  002222C488
19   844BB45P     78906          265945605  004397A906  009655B339  002222C489
20   845BB45P     78907          265945606  004397A907  009655B340  002222C490
21   846BB45P     78908          265945607  004397A908  009655B341  002222C491
22   847BB45P     78909          265945608  004397A909  009655B342  002222C492
23   848BB45P     78910          265945609  004397A910  009655B343  002222C493
24   849BB45P     78911          265945610  004397A911  009655B344  002222C494
25   850BB45P     78912          265945611  004397A912  009655B345  002222C495
26   851BB45P     78913          265945612  004397A913  009655B346  002222C496
27   852BB45P     78914          265945613  004397A914  009655B347  002222C497
28   853BB45P     78915          265945614  004397A915  009655B348  002222C498
29   854BB45P     78916          265945615  004397A916  009655B349  002222C499
30   855BB45P     78917          265945616  004397A917  009655B350  002222C500
31   856BB45P     78918          265945617  004397A918  009655B351  002222C501
32   857BB45P     78919          265945618  004397A919  009655B352  002222C502
33   858BB45P     78920          265945619  004397A920  009655B353  002222C503
34   859BB45P     78921          265945620  004397A921  009655B354  002222C504